/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Projet_V2' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.2.8 */
#define USE_HAL_DRIVER
          #define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
