/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'test' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f2xx.h"

/* Keil::CMSIS Driver:I2C@2.10 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */
#define RTE_Drivers_I2C3                /* Driver I2C3 */
/* Keil::Device:STM32Cube Framework:Classic@1.2.8 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:Common@1.2.8 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.2.8 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.2.8 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.2.8 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:I2C@1.2.8 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:I2S@1.2.8 */
#define RTE_DEVICE_HAL_I2S
/* Keil::Device:STM32Cube HAL:RCC@1.2.8 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:Startup@2.2.2 */
#define RTE_DEVICE_STARTUP_STM32F2XX    /* Device Startup for STM32F2 */


#endif /* RTE_COMPONENTS_H */
